### ISSUE TITLE
Styling System Set Up

### ISSUE THREAD

**Issue by Cleop** [charterindex/application#21]
As a user
I want to see consistency and alignment in the appearance of the site
So that I feel the trust and professionalism in the brand and so that I have a smooth and enjoyable user experience.

The site has a lot of content and for this reason, consistency and order are key components of @nogaibar's designs. She has created a well defined style guide and grid structure that need setting up before work begins to act as the foundation for all styling. 

This issue will outline how we will go about setting up these foundations (the individual points will be created as separate issues):
- [x] Add postcss #22
- [x] Create a custom tachyons file using `tachyons-custom` #23
- [x] Create the 7 font size/style/colour/line height/ font spacing presets (including getting the fonts from Google fonts) #26
- [x] Create the 6 spacing presets and border radius 3px #27
- [x] Create Max width/margin grid view (1080px/1280px) #28
- [x] Create grid structures (1/2, 1/3, 1/4, 2/3) #29

**Comment by Cleop** [comment]
Clsoing as all issues in this epic are now closed/complete 👍
