### ISSUE TITLE
Initial Project Set Up

### ISSUE THREAD

**Issue by Cleop** [charterindex/application#7]
- [x] Set up server, #11 
- [x] Set up tests to access the API #12 
- [x] Add Codecov (depending on account details specified in #5)
- [x] Set up Google Analytics (depending on account details specified in #5)
- [x] Set up Heroku (depending on account details specified in #5)
- [x] Add tachyons:
`<link rel="stylesheet" href="https://unpkg.com/tachyons@4.9.1/css/tachyons.min.css"/>`

**Comment by SimonLab** [comment]
We might want to keep an eye on Tachyons:
![image](https://user-images.githubusercontent.com/6057298/37702084-5014a1b8-2ce9-11e8-8b5e-4d1fe7351d2a.png)

**Comment by Cleop** [comment]
I've done the Google Analytics set up:
![image](https://user-images.githubusercontent.com/16775804/37720300-e9638eda-2d1e-11e8-80f9-d733a1ab6c5b.png)

**Comment by SimonLab** [comment]
#15 is now merged and the server is now running on Heroku
